# -*- coding: utf-8 -*-
"""spotify 2 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KMWoRTQf4TRa9zPEf7aaPbJBjMI3WGkR
"""

import streamlit as st
import requests

st.set_page_config(page_title="Melodies", layout="wide", page_icon="🎵")

st.markdown("""
<style>
.stApp { background-color: #000000; color: white; }
[data-testid="stSidebar"] { background-color: #000000; border-right: 1px solid #282828; }

.tile {
    padding: 25px;
    border-radius: 15px;
    text-align: center;
    border: 1px solid #333;
    transition: 0.3s;
    font-weight: bold;
    font-size: 18px;
}
.tile:hover {
    background-color: #1DB954;
    color: black;
    transform: scale(1.05);
}

.stButton>button {
    background-color: #1DB954;
    color: white;
    border-radius: 20px;
    font-weight: bold;
    width: 100%;
    border: none;
}
</style>
""", unsafe_allow_html=True)

# --- SESSION STATE ---
if "view" not in st.session_state:
    st.session_state.view = "home"
if "selected_artist" not in st.session_state:
    st.session_state.selected_artist = None
if "playing_track" not in st.session_state:
    st.session_state.playing_track = None
if "liked_songs" not in st.session_state:
    st.session_state.liked_songs = []

# --- API ---
BASE_URL = "https://discoveryprovider.audius.co/v1"

def fetch_tracks(query):
    try:
        url = f"{BASE_URL}/tracks/search?query={query}&app_name=STREAMLITIFY"
        r = requests.get(url, timeout=5)
        return r.json().get('data', [])
    except:
        return []

# --- TEXT TILE FUNCTION ---
def text_tile(item, key):
    st.markdown(f'<div class="tile">{item["label"]}</div>', unsafe_allow_html=True)
    return st.button("Open", key=key)

# --- DATA ---
MOODS = [
    {"label": " Need Motivation?",   "tags": "energetic+upbeat",  "img": "motivation.jpeg"},
    {"label": "In Love?",            "tags": "romantic+love",     "img": "love.jpeg"},
    {"label": " Have Some Fun",       "tags": "happy+fun",         "img": "fun.jpeg"},
    {"label": " Don't Be Sad Diva",   "tags": "sad+emotional",     "img": "sad.jpeg"},
    {"label": " Main Character Aura", "tags": "epic+powerful",     "img": "aura.jpeg"},
    {"label": "Late Night Thoughts", "tags": "chill+melancholic", "img": "latenight.jpeg"},
]

ERAS = [
    {"label": "✦ 80s ✦", "tags": "synthpop+newwave+disco", "img": "80s.jpeg"},
    {"label": "✦ 90s ✦", "tags": "grunge+rnb+alternative", "img": "90s.jpeg"},
    {"label": "✦ 00s ✦", "tags": "indie+pop+punk",         "img": "00s.jpeg"},
    {"label": "✦ 10s ✦", "tags": "electronic+hiphop+edm",  "img": "10s.jpeg"},
    {"label": "✦ NOW ✦", "tags": "pop+lofi+trap",           "img": "now.jpeg"},
]

# --- SIDEBAR ---
with st.sidebar:
    st.title("🎵 Melodies")
    if st.button(" Home"):
        st.session_state.view = "home"
        st.rerun()
    if st.button(" Search"):
        st.session_state.view = "search"
        st.rerun()
    if st.button(" Moods"):
        st.session_state.view = "moods"
        st.rerun()
    if st.button(" Time Machine"):
        st.session_state.view = "eras"
        st.rerun()
    if st.button(" Library"):
        st.session_state.view = "library"
        st.rerun()

# --- VIEWS ---

# LIBRARY
if st.session_state.view == "library":
    st.header("Your Library")
    if not st.session_state.liked_songs:
        st.info("No liked songs yet.")
    else:
        for i, track in enumerate(st.session_state.liked_songs):
            col1, col2 = st.columns([5, 1])
            col1.write(f" {track['title']}")
            if col2.button("Play", key=f"lib_{i}"):
                st.session_state.playing_track = track
                st.rerun()

# MOODS
elif st.session_state.view == "moods":
    st.title(" Mood Picker")
    
    st.markdown("""
    <style>
    [data-testid="stImage"] img {
        height: 300px;
        object-fit: cover;
        width: 100%;
        border-radius: 15px;
    }
    </style>
    """, unsafe_allow_html=True)
    
    cols = st.columns(2)
    for i, mood in enumerate(MOODS):
        with cols[i % 2]:
            st.image(mood["img"], use_column_width=True)
            if st.button(mood["label"], key=f"mood_{i}"):
                st.session_state.selected_artist = mood["tags"]
                st.session_state.view = "artist_profile"
                st.rerun()

# ERAS
elif st.session_state.view == "eras":
    st.title("Time Machine")
    
    st.markdown("""
    <style>
    [data-testid="stImage"] img {
        height: 300px;
        object-fit: cover;
        width: 100%;
        border-radius: 15px;
    }
    </style>
    """, unsafe_allow_html=True)
    
    cols = st.columns(5)
    for i, era in enumerate(ERAS):
        with cols[i]:
            if era["img"]:
                st.image(era["img"], use_column_width=True)
            if st.button(era["label"], key=f"era_{i}"):
                st.session_state.selected_artist = era["tags"]
                st.session_state.view = "artist_profile"
                st.rerun()

# SEARCH
elif st.session_state.view == "search":
    st.header("Search")
    query = st.text_input("Search music...")
    if query:
        results = fetch_tracks(query)
        for t in results[:10]:
            col1, col2 = st.columns([5, 1])
            col1.write(f"{t['title']} - {t['user']['name']}")
            if col2.button("▶️", key=t['id']):
                st.session_state.playing_track = {
                    "title": t['title'],
                    "url": f"{BASE_URL}/tracks/{t['id']}/stream?app_name=ST"
                }
                st.rerun()

# ARTIST / RESULTS
elif st.session_state.view == "artist_profile":
    artist = st.session_state.selected_artist
    if st.button("← Back"):
        st.session_state.view = "home"
        st.rerun()

    st.header(f"Tracks for: {artist}")
    tracks = fetch_tracks(artist)
    for t in tracks[:10]:
        c1, c2, c3 = st.columns([4, 1, 1])
        c1.write(t['title'])
        if c2.button("▶ play", key=f"res_play_{t['id']}"):
            st.session_state.playing_track = {
                "title": t['title'],
                "url": f"{BASE_URL}/tracks/{t['id']}/stream?app_name=ST"
            }
            st.rerun()
        if c3.button("❤️ save", key=f"like_{t['id']}"):
            st.session_state.liked_songs.append({
                "title": t['title'],
                "url": f"{BASE_URL}/tracks/{t['id']}/stream?app_name=ST"
            })
            st.toast("Saved!")

# HOME
else:
    st.title("🎵 Welcome")

    st.subheader("Popular Artists")
    artists = ["Adele", "Billie Eilish", "Tamino"]
    cols = st.columns(3)

    for i, artist in enumerate(artists):
        with cols[i]:
            st.markdown(f'<div class="tile">{artist}</div>', unsafe_allow_html=True)
            if st.button("Explore", key=f"a_{i}"):
                st.session_state.selected_artist = artist
                st.session_state.view = "artist_profile"



    # --- BOTTOM SECTION: TRENDING TRACKS (ANIMATED PICTURES) ---
    st.subheader("Trending Mixes")
    trending_mixes = [
        {"name": "Midnight Chill", "img": "https://picsum.photos/id/12/400/400", "query": "Chill"},
        {"name": "Focus Beats", "img": "https://picsum.photos/id/15/400/400", "query": "Lofi"},
        {"name": "Top Pop", "img": "https://picsum.photos/id/26/400/400", "query": "Pop"},
        {"name": "Indie Vibes", "img": "https://picsum.photos/id/37/400/400", "query": "Indie"}
    ]

    t_cols = st.columns(4)
    for i, mix in enumerate(trending_mixes):
        with t_cols[i]:
            st.markdown(f'<div class="track-card"><img src="{mix["img"]}" style="width:100%"></div>', unsafe_allow_html=True)
            if st.button(f"Play {mix['name']}", key=f"mix_{i}"):
                st.session_state.selected_artist = mix['query']
                st.session_state.view = "artist_profile"
                st.rerun()


# PLAYER
if st.session_state.playing_track:
    st.markdown("---")
    curr = st.session_state.playing_track
    st.write(f"🎧 Now Playing: {curr['title']}")
    st.audio(curr['url'])
